package mediasoupgo

import "time"

// WorkerLogLevel represents logging levels for the media worker subprocesses.
type WorkerLogLevel string

const (
	LogLevelDebug WorkerLogLevel = "debug"
	LogLevelWarn  WorkerLogLevel = "warn"
	LogLevelError WorkerLogLevel = "error"
	LogLevelNone  WorkerLogLevel = "none"
)

// WorkerLogTag represents log tags for debugging.
type WorkerLogTag string

const (
	LogTagInfo      WorkerLogTag = "info"
	LogTagIce       WorkerLogTag = "ice"
	LogTagDtls      WorkerLogTag = "dtls"
	LogTagRtp       WorkerLogTag = "rtp"
	LogTagSrtp      WorkerLogTag = "srtp"
	LogTagRtcp      WorkerLogTag = "rtcp"
	LogTagRtx       WorkerLogTag = "rtx"
	LogTagBwe       WorkerLogTag = "bwe"
	LogTagScore     WorkerLogTag = "score"
	LogTagSimulcast WorkerLogTag = "simulcast"
	LogTagSvc       WorkerLogTag = "svc"
	LogTagSctp      WorkerLogTag = "sctp"
	LogTagMessage   WorkerLogTag = "message"
)

// WorkerSettings holds configuration options for a Worker.
type WorkerSettings struct {
	// LogLevel is the logging level for logs generated by the media worker subprocesses.
	// Valid values are "debug", "warn", "error", and "none". Default is "error".
	LogLevel *WorkerLogLevel

	// LogTags are log tags for debugging.
	LogTags []WorkerLogTag

	// RtcMinPort is the minimum RTC port for ICE, DTLS, RTP, etc. Default is 10000.
	// Deprecated: Use TransportListenInfo.portRange instead.
	RtcMinPort *int

	// RtcMaxPort is the maximum RTC port for ICE, DTLS, RTP, etc. Default is 59999.
	// Deprecated: Use TransportListenInfo.portRange instead.
	RtcMaxPort *int

	// DtlsCertificateFile is the path to the DTLS public certificate file in PEM format.
	DtlsCertificateFile *string

	// DtlsPrivateKeyFile is the path to the DTLS certificate private key file in PEM format.
	DtlsPrivateKeyFile *string

	// LibwebrtcFieldTrials are field trials for libwebrtc.
	// NOTE: For advanced users only. An invalid value will make the worker crash.
	LibwebrtcFieldTrials *string

	// DisableLiburing disables liburing (io_uring) even if supported.
	DisableLiburing *bool

	// AppData is custom application data.
	AppData AppData
}

// WorkerUpdateableSettings represents settings that can be updated after Worker creation.
type WorkerUpdateableSettings struct {
	LogLevel *WorkerLogLevel
	LogTags  []WorkerLogTag
}

// WorkerResourceUsage represents resource usage fields from uv_rusage_t struct.
type WorkerResourceUsage struct {
	// RuUtime is the user CPU time used (in milliseconds).
	RuUtime time.Duration

	// RuStime is the system CPU time used (in milliseconds).
	RuStime time.Duration

	// RuMaxrss is the maximum resident set size.
	RuMaxrss int64

	// RuIxrss is the integral shared memory size.
	RuIxrss int64

	// RuIdrss is the integral unshared data size.
	RuIdrss int64

	// RuIsrss is the integral unshared stack size.
	RuIsrss int64

	// RuMinflt is the number of page reclaims (soft page faults).
	RuMinflt int64

	// RuMajflt is the number of page faults (hard page faults).
	RuMajflt int64

	// RuNswap is the number of swaps.
	RuNswap int64

	// RuInblock is the number of block input operations.
	RuInblock int64

	// RuOublock is the number of block output operations.
	RuOublock int64

	// RuMsgsnd is the number of IPC messages sent.
	RuMsgsnd int64

	// RuMsgrcv is the number of IPC messages received.
	RuMsgrcv int64

	// RuNsignals is the number of signals received.
	RuNsignals int64

	// RuNvcsw is the number of voluntary context switches.
	RuNvcsw int64

	// RuNivcsw is the number of involuntary context switches.
	RuNivcsw int64
}

// WorkerDump represents the dump data of a Worker.
type WorkerDump struct {
	Pid                    int
	WebRtcServerIds        []string
	RouterIds              []string
	ChannelMessageHandlers struct {
		ChannelRequestHandlers      []string
		ChannelNotificationHandlers []string
	}
	Liburing *struct {
		SqeProcessCount   int64
		SqeMissCount      int64
		UserDataMissCount int64
	}
}

// WorkerEvents defines events emitted by the Worker.
type WorkerEvents struct {
	Died            func(error)
	SubprocessClose func()
	Success         func()
	Failure         func(error)
}

// WorkerObserverEvents defines events emitted by the Worker observer.
type WorkerObserverEvents struct {
	Close           func()
	NewWebRtcServer func(*WebRtcServer)
	NewRouter       func(*Router)
}
